import 'package:flutter/cupertino.dart';

class Product {
  final String? gametype, productId;
  final String? image, name, description;
  final int? price, size;
  final Color? color;
  //final Image? image;

  Product(
      {this.productId,
      this.image,
      this.name,
      this.price,
      this.description,
      this.size,
      this.color,
      this.gametype});
}

List<Product> products = [
  Product(
    gametype: "Football",
    productId: "SPF001",
    name: 'Football',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/football1.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Football",
    productId: "SPF002",
    name: 'Football',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/football2.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Football",
    productId: "SPF003",
    name: 'Football',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/football3.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Football",
    productId: "SPF004",
    name: 'Football',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/football4.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Football",
    productId: "SPF005",
    name: 'Football',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/boot1.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Football",
    productId: "SPF006",
    name: 'Football',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/boot2.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Football",
    productId: "SPF007",
    name: 'Football',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/boot3.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Football",
    productId: "SPF008",
    name: 'Football',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/boot4.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Cricket",
    productId: "SPC001",
    name: 'Cricket',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/cricket1.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Cricket",
    productId: "SPC002",
    name: 'Cricket',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/cricket2.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Cricket",
    productId: "SPC003",
    name: 'Cricket',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/cricket3.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Cricket",
    productId: "SPC004",
    name: 'Cricket',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/cricket4.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Cricket",
    productId: "SPC005",
    name: 'Cricket',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/cricket5.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Cricket",
    productId: "SPC006",
    name: 'Cricket',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/cricket6.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Cricket",
    productId: "SPC007",
    name: 'Cricket',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/cricket7.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Cricket",
    productId: "SPC008",
    name: 'Cricket',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/cricket8.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Cricket",
    productId: "SPC010",
    name: 'Cricket',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/cricket9.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Cricket",
    productId: "SPC011",
    name: 'Cricket',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/cricket10.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Badminton",
    productId: "SPB001",
    name: 'Badminton',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/badminton1.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Badminton",
    productId: "SPB002",
    name: 'Badminton',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/badminton2.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Badminton",
    productId: "SPB003",
    name: 'Badminton',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/badminton3.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Badminton",
    productId: "SPB004",
    name: 'Badminton',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/badminton4.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Badminton",
    productId: "SPB005",
    name: 'Badminton',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/badminton5.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
  Product(
    gametype: "Badminton",
    productId: "SPB006",
    name: 'Badminton',
    price: 850,
    size: 10,
    description: 'Lorem Ipsum',
    image: "images/badminton6.png",
    color: Color.fromRGBO(0, 139, 139, 1),
  ),
];
